name: ride_share_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  shared_preferences: ^2.3.2
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.6
  internet_connection_checker: null
  flutter_animate: ^4.5.0
  dartz: ^0.10.1
  cupertino_icons: ^1.0.6
  http_interceptor: null
  logger: ^2.4.0
  page_transition: ^2.1.0
  intl: ^0.19.0
  flutter_localizations:
        sdk: flutter
  intl_phone_field: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
flutter_intl:
  enabled: true
